name: Ricardo Viajante
favicon: null
layout_spectrum: 0.49549
typography_spectrum: 0.88177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010100'
    - '#c3e2fe'
    - '#0082fe'
    - '#70a8df'
    - '#8f2f03'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
