name: Ricardo Viajante
favicon: null
layout_spectrum: 0.51523
typography_spectrum: 0.16666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#111419'
    - '#9d817d'
    - '#b20b1c'
    - '#23faff'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
