name: Ricardo Viajante
favicon: null
layout_spectrum: 0.25635
typography_spectrum: 0.8260756449308246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#111419'
    - '#9d817d'
    - '#b20b1c'
    - '#23faff'
  brandStrength: 0.625
  lightness: 0.08094373508356512
  saturation: 0.2595812443178147
  rhythmicContrast: 0.019986319122835994
purpose: []
